spring:
  sql:
    init:
      data-locations: classpath:sql/init-quotes.sql
  datasource:
    url: jdbc:h2:mem:quotes
    driverClassName: org.h2.Driver
    username: admin
    password: pa$$w0rd

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console:
      enabled: true