spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/quotes
    driverClassName: org.postgresql.Driver
    data: classpath:sql/init-quotes.sql
    username: admin
    password: pa$$W0rd
    hikari:
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true