spring:
  datasource:
    url: jdbc:h2:mem:fkdb
    driverClassName: org.h2.Driver
    data: classpath:sql/init-quotes.sql
    initialization-mode: always
    username: admin
    password: pa$$W0rd
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true